# Generated by Django 4.1.7 on 2023-02-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authores'},
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=34, null=True, verbose_name='Titulo')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha publicacion')),
                ('author_id', models.ManyToManyField(to='libro.autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['titulo'],
            },
        ),
    ]
