# Generated by Django 4.1.7 on 2023-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author2',
            name='fecha_de_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creacion'),
        ),
    ]
